import {neon} from '@neondatabase/serverless';
import {createHash,createHmac,randomBytes,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
import {lookup} from 'node:dns/promises';
import {localEmbedding,vectorLiteral} from '../../packages/core/src/embedding.ts';
export const AGENT='microai-docs',DAILY_CAP=900,CLIENT_CAP=30,AGENT_CAP=120;
export function db(){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL is not configured');return neon(process.env.DATABASE_URL)}
export function json(data:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
const secret=()=>process.env.AUTH_SECRET||process.env.RATE_LIMIT_SALT||'microai-development-secret';
export function clientHash(req:Request){const ip=req.headers.get('x-nf-client-connection-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]||'unknown';return createHash('sha256').update(`${secret()}:${ip}`).digest('hex').slice(0,32)}
export function signSession(id=randomBytes(18).toString('hex')){const sig=createHmac('sha256',secret()).update(id).digest('hex');return `${id}.${sig}`}
export const newSession=()=>signSession()
export function sessionHash(token=''){const [id,sig]=token.split('.');if(!id||!sig)return null;const expected=createHmac('sha256',secret()).update(id).digest('hex');try{if(!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null}catch{return null}return id.startsWith('acct_')?id.slice(5):createHash('sha256').update(id).digest('hex').slice(0,32)}
export function owner(req:Request){return sessionHash(req.headers.get('x-microai-session')||'')}
export function encrypt(value:string){const key=createHash('sha256').update(secret()).digest(),iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),out=Buffer.concat([c.update(value),c.final()]);return [iv,c.getAuthTag(),out].map(x=>x.toString('base64url')).join('.')}
export function decrypt(value:string){const [a,b,c]=value.split('.').map(x=>Buffer.from(x,'base64url')),d=createDecipheriv('aes-256-gcm',createHash('sha256').update(secret()).digest(),a);d.setAuthTag(b);return Buffer.concat([d.update(c),d.final()]).toString()}
export async function consume(req:Request,agent=AGENT){const sql=db(),client=clientHash(req);const total=await sql`select coalesce(sum(requests),0)::int count from demo_usage where day=current_date`;if(+total[0].count>=DAILY_CAP)return{ok:false,message:"Today's shared allowance is full. Add your own Groq key or try tomorrow."};const agentTotal=await sql`select coalesce(sum(requests),0)::int count from demo_usage where day=current_date and agent_public_id=${agent}`;if(+agentTotal[0].count>=AGENT_CAP)return{ok:false,message:'This agent reached its shared daily allowance. Add your own Groq key for independent limits.'};const own=await sql`insert into demo_usage(day,client_hash,agent_public_id,requests) values(current_date,${client},${agent},1) on conflict(day,client_hash) do update set requests=demo_usage.requests+1,agent_public_id=${agent},updated_at=now() returning requests`;if(+own[0].requests>CLIENT_CAP)return{ok:false,message:'This visitor reached the shared daily limit. Add your own Groq key or try tomorrow.'};return{ok:true}}
export async function retrieve(question:string,agent=AGENT,limit=5){const sql=db(),literal=vectorLiteral(localEmbedding(question));return sql`select source_title,source_url,content,1-(embedding <=> ${literal}::vector) score from knowledge_chunks where agent_public_id=${agent} order by embedding <=> ${literal}::vector limit ${limit}`}
export function allowed(req:Request){const o=req.headers.get('origin');return !o||o.endsWith('.netlify.app')||o.startsWith('http://localhost:')}
export async function safeUrl(raw:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Only public HTTP(S) URLs are allowed');const addresses=await lookup(u.hostname,{all:true});for(const {address} of addresses){if(/^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd|fe80)/i.test(address)||/^172\.(1[6-9]|2\d|3[01])\./.test(address))throw Error('Private-network URLs are blocked')}return u}
export function slug(){return randomBytes(6).toString('base64url').toLowerCase()}
